/*
 * Licensed to Julian Hyde under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.hydromatic.quidem;

import java.util.List;

/** Handles events that result from parsing a file in Quidem (.iq) format.
 *
 * <p>The events are generated by Quidem's parser, and therefore you can write
 * an application that parses a Quidem file by writing a class that implements
 * this interface.
 *
 * <p>If your application generates events an sends the to an EventWriter,
 * you can generate valid Quidem fies.
 */
public interface EventHandler {
  void comment(List<String> lines);

  void use(List<String> lines, String part);

  void ok(List<String> lines, List<String> content);

  void verify(List<String> lines);

  void update(List<String> lines, List<String> content);

  void plan(List<String> lines, List<String> content);

  void type(List<String> lines, List<String> content);

  void error(List<String> lines, List<String> content);

  void skip(List<String> lines);

  void pop(List<String> lines, Quidem.Property property, String propertyName);

  void push(List<String> lines, Quidem.Property property, String propertyName,
      Object value);

  void set(List<String> lines, Quidem.Property property, String propertyName,
      Object value);

  void show(List<String> lines, Quidem.Property property, String propertyName);

  EventHandler ifBegin(List<String> ifLines, List<String> lines,
      List<String> variables);

  void ifEnd(EventHandler h2, List<String> ifLines, List<String> lines,
      List<String> variables);

  void command(Command command);

  void sql(List<String> content, String sql, boolean sort);
}
